services:
  - type: web
    name: squid-ml-api
    env: python
    region: oregon  # or singapore, frankfurt, etc.
    buildCommand: ""
    startCommand: gunicorn backend.app:app --timeout 60 --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PORT
        value: 5000
